AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ecm-smapler

  Sample SAM Template for ecm-smapler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EcmSamplerFetch:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: dist/lambda.handler
      PackageType: Zip
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
      Events:
        FetchtApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
  EcmSamplerSync:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: dist/lambda.handler
      PackageType: Zip
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Timeout: 300
      MemorySize: 4096
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
      Events:
        SyncAPI:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sync
            Method: ANY


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for EcmSampler function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  EcmSamplerFetch:
    Description: "EcmSamplerFetch Lambda Function ARN"
    Value: !GetAtt EcmSamplerFetch.Arn
  EcmSamplerFetchIamRole:
    Description: "Implicit IAM Role created for EcmSamplerFetch function"
    Value: !GetAtt EcmSamplerFetchRole.Arn
  EcmSamplerSync:
    Description: "EcmSamplerSync Lambda Function ARN"
    Value: !GetAtt EcmSamplerSync.Arn
  EcmSamplerSyncIamRole:
    Description: "Implicit IAM Role created for EcmSamplerSync function"
    Value: !GetAtt EcmSamplerSyncRole.Arn
